config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcomes#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  has_many :topics
  has_many :funds

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/disease.rb
class Disease < ActiveRecord::Base
  has_many :funds
  has_many :topics
  has_many :doctors
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :disease
end

app/models/fund.rb
class Fund < ActiveRecord::Base
  belongs_to :disease
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :disease
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/admin/funds/_donate.html.erb
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="PH66LPPKF362Y">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdsourcing</title>
<!--   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> -->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcomes/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<%= csrf_meta_tags %>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">

	<title>Crowdsourcing - A collaborative effort towards the betterment of the world </title>

	<!-- Bootstrap itself -->
	<%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" %>
	<%= stylesheet_link_tag "magister" %>
	<!-- Fonts -->
	<%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" %>
	<link href='http://fonts.googleapis.com/css?family=Wire+One' rel='stylesheet' type='text/css'>
</head>

<!-- use "theme-invert" class on bright backgrounds, also try "text-shadows" class -->
<body class="theme-invert">

<!-- Main (Home) section -->
<section class="section" id="head">
	<div class="container">

		<div class="row">
			<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">

				<!-- Site Title, your name, HELLO msg, etc. -->
				<h1 class="title">C-r-o-w-d-s-o-u-r-c-i-n-g</h1>
				<h2 class="subtitle"></h2>

				<!-- Short introductory (optional) -->
				<h3 class="tagline">
					A collaborative effort towards the betterment of the world
				</h3>

				<!-- Nice place to describe your site in a sentence or two -->
				<p><%= link_to "Join us now", new_admin_admin_user_path , class: "btn btn-default btn-lg" %></p>

			</div> <!-- /col -->
		</div> <!-- /row -->

	</div>
</section>


<!-- Load js libs only when the page is loaded. -->

<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" %>
<%= javascript_include_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js" %>
<%= javascript_include_tag "modernizr.custom.72241" %>
<!-- Custom template scripts -->
<%= javascript_include_tag "magister" %>
</body>
</html>